


cv_prompt: str = "Summarize the following information."

linkedin_prompt: str = ("Summarize the following information with particular focus on the "
                        "headline, about, skills, certifications, recommendations, activity and "
                        "details of their latest job. If a particular data field does not exist "
                        "then just ignore it.")
welcome_prompt: str = """
    Write a friendly, warm onboarding welcome message for a user named {user_name}.
    - The message should be 1-2 sentences, not just a greeting.
    - It should set the stage for a short Q&A about their background.
    - Make it sound inviting and personal.
    Example:
    Hi {user_name}, welcome to the onboarding process! I'll ask you a few questions to get to know you better. Ready? Let's begin.
    """

onboarding_question_prompt: str = f"""
    Create four concise and completely distinct questions for a user's interview prep, each targeting a specific field:
    1. current_work, 2. reason_for_interview, 3. where_in_interview_process, and 4. target_company.
    Each question must:
    Be warm, conversational, and supportive.
    Be exactly one sentence (max 1.5 lines).
    Be substantially different in phrasing, word choice, and sentence structure — no two questions should sound remotely alike.
    Avoid repeating sentence patterns or openings (e.g., no “What’s your…” or “Are you…” across multiple questions).
    Each question should sound natural and tailored only to its specific field.
    Field-specific constraints:

    current_work: Ask about the user’s current role and how long they’ve been in it — don’t reference resumes or LinkedIn.
    reason_for_interview: Ask what’s prompting their prep — include varied examples like switching jobs, growing confidence, or aiming high.
    where_in_interview_process: Ask where they are in the process — include options like just getting started, mid-process, final rounds, or skill-building.
    target_company: Ask about any company or role they’re aiming for — offer the choice to share a job description or say they’re exploring.

    Format the result as a numbered list. Start each line with the bolded field name.
    Example output format:

    current_work:
    reason_for_interview:
    where_in_interview_process:
    target_company:
"""

# current_work: str = "Using the following text as a context ask a question in one sentence" \
#                     "Let’s start with your work — just so I get a sense of the world you operate in." \
#                     "What’s your current role, and how long have you been doing it?" \
#                     "If it’s easier, feel free to link your LinkedIn or drop a resume — totally up to you."

# reason_for_interview: str = "Using the following text as a context ask a question in one sentence" \
#                             "What’s got you preparing for interviews right now?" \
#                             "You don’t need a perfect answer — just what’s true for you." \
#                             "Some folks are job hunting after a layoff. Others are aiming for a big move — a promotion, a better offer, a dream company. " \
#                             "And some just want to get better at telling their story. Which of those feels most like your situation?"

# where_in_interview_process: str  ="Using the following text as a context ask a question in one sentence"\
#                                   "Just so I know how fast to go — where are you in your interview process?"\
#                                   "Still early? Already in the loop? Just sharpening up?"\
#                                   "No pressure either way. This just helps me meet you where you are."

# target_company: str = "Using the following text as a context ask a question in one sentence"\
#                       "Any particular role or company you’ve got your eye on?"\
#                       "You can type something like “PM at Google” or “Marketing lead at a Series A startup.”"\
#                       "Or upload a job description if you’ve got one handy."\
#                       "And if you're still figuring it out, that’s totally fine — we can start general and narrow in as you go."

onboarding_summary_prompt: str = "Create a summary using the following data"

# # Configure the embedding function

# interviewer_question_fetch_prompt = "You are a high level manager of the company. You are taking the interview of a candidate."\
#                                     "The following is the summary generated by our system. Use it and grab the suitable questions from the database"